apiVersion: triggers.tekton.dev/v1
kind: TriggerTemplate
metadata:
  name: ci-template
  namespace: dev
spec:
  params:
    - name: git-repo-url
      description: The Git repository URL
    - name: git-revision
      description: The Git revision (branch)
    - name: git-commit
      description: The Git commit SHA

  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      meta
        generateName: ci-run-
        annotations:
          tekton.dev/git-url: $(params.git-repo-url)
          tekton.dev/git-revision: $(params.git-revision)
          tekton.dev/git-commit: $(params.git-commit)
      spec:
        pipelineRef:
          name: ci-pipeline
        serviceAccountName: build-bot
        params:
          - name: repo-url
            value: $(params.git-repo-url)
          - name: revision
            value: $(params.git-revision)
          - name: image
            value: docker.io/owllabsdocker/test1-owl:latest
          - name: dockerfile
            value: ./Dockerfile
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace