apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-build-push-template
  namespace: test
spec:
  params:
    - name: GIT_URL
    - name: GIT_REVISION
    - name: IMAGE_REPO
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-push-run-
      spec:
        pipelineRef:
          name: pipeline-build-push
        params:
          - name: GIT_URL
            value: $(params.GIT_URL)
          - name: GIT_REVISION
            value: $(params.GIT_REVISION)
          - name: IMAGE_REPO
            value: $(params.IMAGE_REPO)
        workspaces:
          - name: shared-workspace
            emptyDir: {}
          - name: dockerconfig
            configMap:
              name: docker-config

