apiVersion: triggers.tekton.dev/v1
kind: TriggerBinding
metadata:
  name: ci-binding
  namespace: dev
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)
    - name: git-commit
      value: $(body.head_commit.id)