apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: test
spec:
  params:
    - name: GIT_URL
      value: $(body.repository.clone_url)
    - name: GIT_REVISION
      value: $(body.ref)
    - name: IMAGE_REPO
      value: docker.io/owllabsdocker/owllabs

