apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-   # Tekton will append a random suffix
  namespace: test
spec:
  pipelineRef:
    name: build-and-push
  params:
    - name: IMAGE_REPO
      value: docker.io/owllabsdocker/owllabs
    - name: CONTEXT
      value: .   # assumes Dockerfile is at repo root
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: source-pvc   # must exist, holds your source code
    - name: dockerconfig
      secret:
        secretName: regcred     # must exist, contains Docker Hub creds
  podTemplate:
    securityContext:
      runAsUser: 0
      fsGroup: 0

