apiVersion: tekton.dev/v1
kind: PipelineRun
meta
  generateName: build-and-push-run-
  namespace: test
spec:
  pipelineRef:
    name: pipeline-build-push
  params:
    - name: IMAGE_REPO
      value: docker.io/owllabsdocker/owllabs   # ✅ must match your repo
    - name: CONTEXT
      value: .
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    - name: dockerconfig
      configMap:
        name: docker-config
