# pipelinerun.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ci-run-
  namespace: dev
spec:
  pipelineRef:
    name: ci-pipeline

  taskRunSpecs:
    - pipelineTaskName: fetch-source
      serviceAccountName: build-bot
    - pipelineTaskName: build-and-push
      serviceAccountName: build-bot

  params:
    - name: repo-url
      value: https://github.com/owllabsgit/test1-owl.git
    - name: revision
      value: main
    - name: image
      value: docker.io/owllabsdocker/test1-owl:latest
    - name: dockerfile
      value: ./Dockerfile

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace
