# 4 - pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-   # <- This prefix will appear for every run
  namespace: test
spec:
  pipelineRef:
    name: pipeline-build-push
  serviceAccountName: tekton-bot
  params:
    - name: GIT_URL
      value: https://github.com/owllabsgit/test1-owl.git
    - name: GIT_REVISION
      value: main
    - name: IMAGE_REPO
      value: docker.io/owllabsdocker/owllabs
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    - name: dockerconfig
      configMap:
        name: docker-config

