apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-push-
  namespace: test
spec:
  taskRef:
    name: build-and-push
  params:
    - name: IMAGE_REPO
      value: docker.io/owllabsdocker/owllabs
    - name: CONTEXT
      value: .
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: dockerconfig
      configMap:
        name: docker-config

