apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
  namespace: test
spec:
  pipelineRef:
    name: pipeline-build-push
  params:
    - name: GIT_URL
      value: https://github.com/owllabsgit/test1-owl.git
    - name: IMAGE
      value: docker.io/owllabsdocker/owllabs
    - name: CONTEXT
      value: .
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
    - name: dockerconfig
      secret:
        secretName: docker-config

