# eventlistener.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: dev
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-binding                 # ← Your binding name
      template:
        ref: github-trigger-template          # ← Your template name
