apiVersion: v1
kind: Service
metadata:
  name: el-github-listener-nodeport
  namespace: dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: el-github-listener
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

