apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-run-
  namespace: dev
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: ci-pipeline
  params:
    - name: repo-url
      value: https://github.com/owllabsgit/test1-owl.git
    - name: revision
      value: main
    - name: image
      value: docker.io/owllabsdocker/test1-owl:latest
    - name: dockerfile
      value: ./Dockerfile
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace
    - name: dockerconfig
      secret:
        secretName: reg-creds

