apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: dev
spec:
  params:
    - name: repo-url
      type: string
      description: Repository to clone
    - name: revision
      type: string
      description: Branch or tag
      default: main
    - name: image
      type: string
      description: Full image name
    - name: dockerfile
      type: string
      description: Path to Dockerfile
      default: ./Dockerfile
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        kind: Task
        name: fetch-source-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        kind: Task
        name: kaniko-build-push-task
      runAfter:
        - fetch-source
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
      workspaces:
        - name: source
          workspace: shared-workspace

