apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: dev
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: revision
      type: string
      description: Branch or tag
      default: main
    - name: DOCKERFILE
      type: string
      description: Path to Dockerfile
      default: ./Dockerfile
    - name: IMAGE
      type: string
      description: Docker image name
  workspaces:
    - name: shared-workspace
    - name: docker-config
  tasks:
    - name: fetch-source-task
      taskRef:
        name: fetch-source-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: extract-git-sha
      taskRef:
        name: extract-git-sha
      runAfter:
        - fetch-source-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: kaniko-build-push-task
      taskRef:
        name: kaniko-build-push-task
      runAfter:
        - extract-git-sha
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: COMMIT_SHA
          value: $(tasks.extract-git-sha.results.commitSha)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-config
          workspace: docker-config
