apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: dev
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-binding
      template:
        ref: ci-template
      interceptors:
        - cel:
            filter: "body.ref == 'refs/heads/main' && body.head_commit.author.username != 'argocd-image-updater'"

