apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: dev
spec:
  params:
    - name: repo-url
      description: Git repository URL
    - name: revision
      description: Git revision (branch/tag)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: ci-pipeline
        params:
          - name: repo-url
            value: $(params.repo-url)
          - name: revision
            value: $(params.revision)
          - name: image
            value: docker.io/owllabsdocker/test1-owl:latest
          - name: dockerfile
            value: ./Dockerfile
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace
          - name: dockerconfig
            secret:
              secretName: reg-creds

