apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: owllabsdocker/owllabs
    argocd-image-updater.argoproj.io/owllabs.update-strategy: latest
    argocd-image-updater.argoproj.io/owllabs.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/owllabsgit/terraform.git
    targetRevision: main
    path: my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

