apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-push
  namespace: test
spec:
  params:
    - name: GIT_URL
      type: string
    - name: GIT_REVISION
      type: string
      default: main
    - name: IMAGE_REPO
      type: string
    - name: CONTEXT
      type: string
      default: .
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE_REPO
          value: $(params.IMAGE_REPO)
        - name: CONTEXT
          value: $(params.CONTEXT)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig

