# pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: dev
spec:
  params:
    - name: repo-url
      type: string
      description: Repository to clone
    - name: revision
      type: string
      description: Branch or tag
      default: main
    - name: image
      type: string
      description: Full image name, e.g., docker.io/owllabsdocker/test1-owl:latest
    - name: dockerfile
      type: string
      description: Path to Dockerfile
      default: ./Dockerfile

  workspaces:
    - name: shared-workspace

  tasks:
    - name: fetch-source
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      taskRef:
        kind: Task
        name: build-and-push-task
      runAfter:
        - fetch-source
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
      workspaces:
        - name: source
          workspace: shared-workspace
