# pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build-push
  namespace: test
spec:
  params:
    - name: IMAGE_REPO
      type: string
    - name: CONTEXT
      type: string
      default: .

  workspaces:
    - name: source
    - name: dockerconfig

  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE_REPO
          value: $(params.IMAGE_REPO)
        - name: CONTEXT
          value: $(params.CONTEXT)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
