# pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-push
  namespace: test
spec:
  params:
    - name: GIT_URL
      type: string
      description: The Git repository URL to clone
    - name: GIT_REVISION
      type: string
      default: main
      description: The Git revision (branch, tag, SHA)
    - name: IMAGE_REPO
      type: string
      description: Full image repo (e.g. docker.io/owllabsdocker/owllabs)
    - name: CONTEXT
      type: string
      default: .
      description: Context path inside the repo for Docker build
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: fetch-repo
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
    - name: build-and-push
      runAfter:
        - fetch-repo
      taskRef:
        kind: Task
        name: build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_REVISION
          value: $(params.GIT_REVISION)
        - name: IMAGE_REPO
          value: $(params.IMAGE_REPO)
        - name: CONTEXT
          value: $(params.CONTEXT)
