apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-push
  namespace: test
spec:
  params:
    - name: GIT_URL
      type: string
      description: https://github.com/owllabsgit/test1-owl.git
    - name: IMAGE
      type: string
      description: owllabsdocker/owllabs:latest
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      runAfter:
        - fetch-source
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace

