# 0 - serviceaccount-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-bot
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deployer
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","create","update","patch","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","update","patch","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deployer-binding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: tekton-bot
    namespace: test
roleRef:
  kind: Role
  name: tekton-deployer
  apiGroup: rbac.authorization.k8s.io

