apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-bot
  namespace: test
secrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-bot-role
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-bot-binding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: tekton-bot
    namespace: test
roleRef:
  kind: Role
  name: tekton-bot-role
  apiGroup: rbac.authorization.k8s.io
