apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push-image
  namespace: test
spec:
  params:
    - name: IMAGE_REPO
      type: string
      description: "Registry and repo, e.g. docker.io/owllabsdocker/owllabs"
    - name: CONTEXT
      type: string
      default: .
      description: "Build context directory inside the source"

  results:
    - name: image-tag
      description: "Generated image tag, e.g. build-1234567890"
    - name: full-image
      description: "Full image name with tag, e.g. docker.io/owllabsdocker/owllabs:build-1234567890"

  workspaces:
    - name: source
      description: "Source code including Dockerfile"
    - name: dockerconfig
      description: "Docker config.json for registry authentication"

  steps:
    # Step 1: Generate a unique tag
    - name: generate-tag
      image: alpine:latest
      script: |
        TAG="build-$(date +%s)"
        IMAGE="$(params.IMAGE_REPO):${TAG}"
        echo "Generated tag: ${TAG}"
        echo "Full image: ${IMAGE}"
        echo -n "${TAG}" > $(results.image-tag.path)
        echo -n "${IMAGE}" > $(results.full-image.path)

    # Step 2: Build and push the image using Kaniko
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(results.full-image.path)
        - --verbosity=info
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

