# ✅ Updated Task: Remove the entire 'update-git-manifests' step
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: test
spec:
  params:
    - name: IMAGE
      type: string
      description: Full image name with tag (e.g., docker.io/owllabsdocker/owllabs:build-123)
    - name: CONTEXT
      type: string
      default: .
      description: Build context directory
  workspaces:
    - name: source
      description: Source code to build
    - name: dockerconfig
      description: Docker config.json for pushing image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --verbosity=info
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
