# task-build-and-push.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: test
spec:
  params:
    - name: IMAGE_REPO
      type: string
      description: "docker.io/owllabsdocker/owllabs"
    - name: CONTEXT
      type: string
      default: .
      description: "Build context"

  workspaces:
    - name: source
      description: "Source code"
    - name: dockerconfig
      description: "Docker config.json"

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE_REPO):latest
        - --push-retry=3
        - --verbosity=info
        - --cache=true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      configMap:
        name: docker-config
        items:
          - key: config.json
            path: config.json
