apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: test
spec:
  params:
    - name: IMAGE_REPO
      type: string
      description: "Registry and repo, e.g. docker.io/owllabsdocker/owllabs"
    - name: CONTEXT
      type: string
      default: .
      description: "Build context directory inside the source"

  results:
    - name: image-tag
      description: "The generated tag, e.g. build-1723724580"
    - name: built-image
      description: "Full image name with tag, e.g. docker.io/owllabsdocker/owllabs:build-1723724580"

  workspaces:
    - name: source
      description: "Source code with Dockerfile"
    - name: dockerconfig
      description: "Docker config.json for registry authentication"

  steps:
    # Step 1: Generate a unique tag
    - name: generate-tag
      image: alpine:latest
      script: |
        TAG="build-$(date +%s)"
        IMAGE="$(params.IMAGE_REPO):${TAG}"

        echo "Generated tag: ${TAG}"
        echo "Full image: ${IMAGE}"

        # Save results for later steps
        echo -n "${TAG}" > $(results.image-tag.path)
        echo -n "${IMAGE}" > $(results.built-image.path)

    # Step 2: Build and push with unique tag
    - name: build-and-push-tagged
      image: gcr.io/kaniko-project/executor:v1.23.2
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE_REPO):$(cat $(results.image-tag.path))
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    # Step 3: Also update :latest (optional)
    - name: build-and-push-latest
      image: gcr.io/kaniko-project/executor:v1.23.2
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE_REPO):latest
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

