apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: test
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
      default: .
    - name: MANIFEST_REPO_URL
      type: string
    - name: MANIFEST_REPO_BRANCH
      type: string
      default: main
    - name: MANIFEST_REPO_PATH
      type: string
      default: my-app
  workspaces:
    - name: source
    - name: dockerconfig
    - name: git-ssh  # for pushing if private repo (optional)
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --verbosity=info
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    - name: update-git-manifests
      image: alpine/git
      script: |
        set -e
        # Configure git
        git config --global user.email "ci-bot@yourorg.com"
        git config --global user.name "CI Bot"

        # Clone manifests repo
        git clone --branch $(params.MANIFEST_REPO_BRANCH) $(params.MANIFEST_REPO_URL) /workspace/manifests

        cd /workspace/manifests/$(params.MANIFEST_REPO_PATH)

        # Replace image tag in deployment.yaml
        sed -i 's|image: owllabsdocker/owllabs:.*|image: $(params.IMAGE)|' deployment.yaml

        # Commit & push changes
        git add deployment.yaml
        git commit -m "Update image to $(params.IMAGE)"
        git push origin $(params.MANIFEST_REPO_BRANCH)
      volumeMounts:
        - name: git-ssh
          mountPath: /root/.ssh

